### ISSUE TITLE
AttributeError: module 'pyparam.params' has no attribute 'vcf'

### ISSUE THREAD

**Issue by plrlhb12** [pwwang/vcfstats#1]
This seems a really nice tool in exploring QC of vcf. I wanted to give a try. After I installed it in my mac using `pip install vcfstats` and run the example vcf file,  I got the error as below. Do you have any idea or suggestion on wha the problem and solutions are. Thank you

$ vcfstats --vcf examples/sample.vcf \
> --outdir examples/ \
> --formula 'COUNT(1) ~ CONTIG' \
> --title 'Number of variants on each chromosome' \
> --config examples/config.toml

Traceback (most recent call last):
  File "/Users/pengl7/opt/anaconda3/envs/genomics/bin/vcfstats", line 5, in <module>
    from vcfstats import main
  File "/Users/pengl7/opt/anaconda3/envs/genomics/lib/python3.7/site-packages/vcfstats/__init__.py", line 18, in <module>
    params.vcf.required = True
AttributeError: module 'pyparam.params' has no attribute 'vcf'

**Comment by pwwang** [comment]
This is due to the pyparam package update. 
A temporary solution is to install the right version of pyparam:
```shell
pip install pyparam==0.3.2
```

I will work on a version to adapt the latest pyparam

**Comment by plrlhb12** [comment]
Thank you for the quick response. Tried again after install the pyparam 0.3.2, but still got the same error message.

**Comment by pwwang** [comment]
My guess is that pyparam is still not downgraded. Anyways, I will work on it ASAP, and will probably release it today or tmr. I will keep you posted on this post.

**Comment by pwwang** [comment]
I believe this is fixed at `0.6.0`. Please try `pip install -U vcfstats` to upgrade it.

Closing this, but feel free to reopen if this issue still persists.
