### ISSUE TITLE
option --title never works

### ISSUE THREAD

**Issue by lmanchon** [pwwang/vcfstats#11]
--Hi,

this command:
 vcfstats --vcf ERR5875663.snpeff.vcf --outdir examples --formula 'COUNT(1, group=VARTYPE) ~ CHROM' --title 'ERR5875663' --config config.toml

doesn't print the title on plot, just used to name the output file.

Why ?

**Comment by pwwang** [comment]
Currently, the title is not added to the plot. You can use `--ggs 'ggtitle("<your title>")'` to add it.

**Comment by lmanchon** [comment]
ok, i'm going to try that.
thank you.

**Comment by pwwang** [comment]
`--title` is now written to the figure by default at #12 (0.2.0).
