### ISSUE TITLE
Config file for the vcfstats

### ISSUE THREAD

**Issue by DenisGoryunov** [pwwang/vcfstats#13]
Hi,
Thank you for developing vcfstats software! Could you advise me please, where i may find the "config.toml" file to run vcfstats? 

Regards,
Denis

**Comment by pwwang** [comment]
You can find one here:

https://github.com/pwwang/vcfstats/blob/master/examples/config.toml

as well as some documentation about it here:

https://pwwang.github.io/vcfstats/configfile/

**Comment by DenisGoryunov** [comment]
Thank you  very much! Now vcfstats is working.
