### ISSUE TITLE
cyvcf2 warnings while parsing the vcf file

### ISSUE THREAD

**Issue by DenisGoryunov** [pwwang/vcfstats#14]
Hi,

There are a number of warnings in the log file after vcfstats execution. Please find the examples below:

[02/02/22 22:21:42] WARNING  (cyvcf2) [W::vcf_parse] Contig '1D' is not defined
                             in the header. (Quick workaround: index the file
                             with tabix.)
[02/02/22 22:21:42] WARNING  (cyvcf2) [W::vcf_parse] INFO 'QualityScore' is not
                             defined in the header, assuming Type=String
My question is, can i just ignore all of that warnings, because these are not important?

Regards,
Denis

**Comment by pwwang** [comment]
Yes, you can.

**Comment by DenisGoryunov** [comment]
Thanks for your reply.
