### ISSUE TITLE
vcfstats command not recognized

### ISSUE THREAD

**Issue by aliakeefe** [pwwang/vcfstats#18]
Hello, I followed the installation instructions by using `pip -U install` and the command `vcfstats`  is still not recognized. When I ran the installation command I got no errors. Do I have to clone the repository as well?

Thanks

**Comment by pwwang** [comment]
Have you tried `pip install -U vcfstats`?

**Comment by aliakeefe** [comment]
Yes, that was the first thing I tried, sorry for not being clear.

**Comment by pwwang** [comment]
Then are you able to run `python -m vcfstats`?

**Comment by aliakeefe** [comment]
Ah, yes I was able to run this.

**Comment by pwwang** [comment]
Let me know which versions of these you are using: python, pip and vcfstats.

You could probably try upgrading your `pip` and reinstalling vcfstats. 
`pip install -U pip`

The fallback solution is to make an alias `vcfstats` to `python -m vcfstats`.

**Comment by pwwang** [comment]
Closing. Feel free to reopen if the issue still exists.
