### ISSUE TITLE
Vcfstats doesn't show the MNPs?

### ISSUE THREAD

**Issue by LaurenceKuhl** [pwwang/vcfstats#3]
Hi there,

I was trying to produce plots with vcfstats and it doesn't seem to represent MNPs (multiple nucleotide polymorphisms) as reported by bcftools stats ?
I also notice a discrepancy in SNPs/Indels between bcftools and vcfstats, has this ever happened to you ?
I'll take any information I can get, thanks!
Best,
Laurence

**Comment by pwwang** [comment]
Hi Laurence,

vcfstats does not have any internal variant filtering, meaning all should be included.
Could you provide a minimal example vcf file and the commands of both vcfstats and bcftools you used?

Thanks,
Panwen

**Comment by pwwang** [comment]
Closing as lacking information. Feel free to reopen.
