### ISSUE TITLE
Matplotlib Contour Install Error

### ISSUE THREAD

**Issue by gk7279** [pwwang/vcfstats#31]
I have installed vcfstats using pip.

When I try to say vcfstats --help, it tells me

ModuleNotFoundError: No module named 'matplotlib._contour'

Any idea why?

I did install matplotlib through pip and python3-matplotlib is also installed via apt.

**Comment by pwwang** [comment]
It's because of the matplotlib version. 
You need to downgrade matplotlib to 3.5

See also: https://stackoverflow.com/questions/73792756/plotnine-is-broken-with-matplotlib-3-6
