### ISSUE TITLE
Labelling

### ISSUE THREAD

**Issue by kkmll** [pwwang/vcfstats#38]
On het hom plot I would like to use labels on graph as HET & HOM not like HET & HOM_ALT, so how can I edit that part?

and on GQ vs depth graph I want the chrom labels in order as 1,2,3, etc but with the current code it continues as 1, 10, 2 etc, so how can I change it?

thanks..

**Comment by pwwang** [comment]
```shell
vcfstats --vcf examples/sample.vcf \                                  
        --outdir examples/ \
        # or simply
        # --formula 'GTTYPEs[HET,HOM_ALT]{0} ~ CHROM' \
        --formula 'COUNT(1, group=GTTYPEs[HET,HOM_ALT]{0}) ~ CHROM' \
        --title 'Mutant genotypes on each chromosome (sample 1)' \
        --config examples/config.toml \
        --ggs 'scale_fill_discrete(labels=["HET", "HOM"])'
```
![mutant-genotypes-on-each-chromosome-sample-1 col](https://user-images.githubusercontent.com/1188067/217898452-eb4338e3-d8c3-4318-960f-46e16815551e.png)

```shell
vcfstats --vcf examples/sample.vcf \                                                          
        --outdir examples/ \
        --formula 'MEAN(GQs{0}) ~ MEAN(DEPTHs{0}, group=CHROM)' \
        --title 'GQ vs depth (sample 1)' \
        --config examples/config.toml \
        --ggs 'scale_color_discrete(limits=["1","2","3","4","5","6","7","8","9","10","X"])'
```

![gq-vs-depth-sample-1 scatter](https://user-images.githubusercontent.com/1188067/217897425-36c2372f-fcc6-4eaa-acb9-789c4ab5c22a.png)

**Comment by kkmll** [comment]
thnks
