### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by dtabb73** [pwwang/vcfstats#4]
There seems to be a problem with the call to MSVC cl.exe that gets triggered during the install of this software.  On a fresh install of Python 3.9.5 and the MSVC 2019 tools, I receive this error in response to "python -m pip install vcfstats":

C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ihtslib -Icyvcf2 -IC:\Python3\lib\site-packages\numpy\core\include -IC:\Python3\include -IC:\Python3\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt /Tccyvcf2/cyvcf2.c/Fobuild\temp.win-amd64-3.9\Release\cyvcf2/cyvcf2.obj -Wno-sign-compare -Wno-unused-function -Wno-strict-prototypes -Wno-unused-result -Wno-discarded-qualifiers

cl : Command line error D8021 : invalid numeric argument '/Wno-sign-compare'
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.28.29910\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2

**Comment by pwwang** [comment]
Have you tried installing other packages this way?

**Comment by dtabb73** [comment]
Yes, I installed Biopython successfully, moments before attempting to install vcfstats.

**Comment by pwwang** [comment]
Could you try `python -m pip install -r requirements.txt`?
I doubt it's because of the dependencies since vcfstats itself doesn't require any C/C++ compilation.

**Comment by dtabb73** [comment]
I downloaded requirements.txt from here: https://raw.githubusercontent.com/pwwang/vcfstats/master/requirements.txt.

When I ran the command line you suggested, I produced this error:

  Attempting uninstall: pyparam
    Found existing installation: pyparam 0.4.8
    Uninstalling pyparam-0.4.8:
      Successfully uninstalled pyparam-0.4.8
    Running setup.py install for lark-parser ... done
    Running setup.py install for cyvcf2 ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Python3\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\dta
bb\\AppData\\Local\\Temp\\pip-install-0ptj_ka_\\cyvcf2_3b57fdcdc530494a92abc5423cefed3f\\setup.py'"'"'; __file__='"'"'C:
\\Users\\dtabb\\AppData\\Local\\Temp\\pip-install-0ptj_ka_\\cyvcf2_3b57fdcdc530494a92abc5423cefed3f\\setup.py'"'"';f = g
etattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools impor
t setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"
'exec'"'"'))' install --record 'C:\Users\dtabb\AppData\Local\Temp\pip-record-r_p8zrtd\install-record.txt' --single-versi
on-externally-managed --compile --install-headers 'C:\Python3\Include\cyvcf2'
         cwd: C:\Users\dtabb\AppData\Local\Temp\pip-install-0ptj_ka_\cyvcf2_3b57fdcdc530494a92abc5423cefed3f\

         [a bunch of other lines appear here]

             building 'cyvcf2.cyvcf2' extension
    creating build\temp.win-amd64-3.9
    creating build\temp.win-amd64-3.9\Release
    creating build\temp.win-amd64-3.9\Release\cyvcf2
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\bin\HostX86\x64\cl.exe /c /
nologo /Ox /W3 /GL /DNDEBUG /MD -Ihtslib -Icyvcf2 -IC:\Python3\lib\site-packages\numpy\core\include -IC:\Python3\include
 -IC:\Python3\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\include
 -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.
0.19041.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um -IC:\Program Files (x86)\Windows Kits\
10\include\10.0.19041.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt /Tccyvcf2/cyvcf2.c
/Fobuild\temp.win-amd64-3.9\Release\cyvcf2/cyvcf2.obj -Wno-sign-compare -Wno-unused-function -Wno-strict-prototypes -Wno
-unused-result -Wno-discarded-qualifiers
    cl : Command line error D8021 : invalid numeric argument '/Wno-sign-compare'
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.28.29910\\bi
n\\HostX86\\x64\\cl.exe' failed with exit code 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Python3\python.exe' -u -c 'import io, os, sys, setuptools, tokenize;
sys.argv[0] = '"'"'C:\\Users\\dtabb\\AppData\\Local\\Temp\\pip-install-0ptj_ka_\\cyvcf2_3b57fdcdc530494a92abc5423cefed3f
\\setup.py'"'"'; __file__='"'"'C:\\Users\\dtabb\\AppData\\Local\\Temp\\pip-install-0ptj_ka_\\cyvcf2_3b57fdcdc530494a92ab
c5423cefed3f\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.St
ringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();
exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\dtabb\AppData\Local\Temp\pip-record-r_p8zrtd\i
nstall-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Python3\Include\cyvcf2' Check the
 logs for full command output.

**Comment by pwwang** [comment]
Looks like `cyvcf2` has problems being installed on Windows. See https://github.com/brentp/cyvcf2/issues/116 and https://github.com/brentp/cyvcf2/issues/90.

Regarding this error `cl : Command line error D8021 : invalid numeric argument '/Wno-sign-compare'`, are you able to remove those `/Wno-xxx` options and run the compiling command again, according to https://stackoverflow.com/questions/45769159/cl-command-line-error-d8021-invalid-numeric-argument-wno-cpp ?

**Comment by pwwang** [comment]
Since cyvcf2 doesn't support Windows, vcfstats won't support Windows either.

Closing this.
