### ISSUE TITLE
Increase memory allocation

### ISSUE THREAD

**Issue by gnxsf** [pwwang/vcfstats#44]
Is there an option for specifying the memory allocation to vcfstats? My job keeps failing due to out of memory issues, even though I'm only running one chromosome and I've requested a worker with 125 Gb of memory.

**Comment by pwwang** [comment]
There is no memory allocation involved in vcfstats. Are you trying to do some aggregation stats? If so, we do need an option for the buffer size.

**Comment by gnxsf** [comment]
Yes, it seems to fail when attempting to calculate the sample-level read depth using the custom macro defined below. The ```dp[dp >= 0]``` statement is to remove the large negative number associated with a missing value.

```
@continuous
def gt_DP(variant):
    dp = variant.format('DP').flatten()
    return(dp[dp >= 0])
```

**Comment by pwwang** [comment]
That's actually wired. If this is the only stat you are using, the variant should be processed one at a time. It should not consume that much memory, unless there is a leak. 

How many variants are there in your VCF file? Would you mind sharing it, together with the command to see if I can reproduce it?

**Comment by gnxsf** [comment]
I work for a private company, so I am unable to share the data in order to reproduce the problem - sorry. However, there are several other stats I'm calculating at the same time, and the file is very large (probably about 20 Mil variants). Below is the list of stats I'm calculating. When I remove the gt_DP macro, I'm able to get the job to run successfully if I allocated 250 Gb of memory.

```
@continuous
def DP(variant):
    return variant.INFO.get("DP")

@continuous
def AF(variant):
    return variant.INFO.get("AF")

@continuous
def MQ(variant):
    return variant.INFO.get("MQ")

@continuous
def MQRankSum(variant):
    MQRS = variant.INFO.get("MQRankSum")

@continuous
def SOR(variant):
    return variant.INFO.get("SOR")

@continuous
def QD(variant):
    return variant.INFO.get("QD")

@continuous
def BaseQRankSum(variant):
    return variant.INFO.get("BaseQRankSum")

@continuous
def ReadPosRankSum(variant):
    return variant.INFO.get("ReadPosRankSum")

@categorical
def GT(variant):
    gts = variant.genotypes
    return ['/'.join(one_samp[0:2]) for one_samp in gts]

@continuous
def gt_DP(variant):
    dp = variant.format('DP').flatten()
    return(dp[dp >= 0])

@continuous
def percent_het(variant):
    nocall_list = [gts[0:2].count(-1) for gts in variant.genotypes]
    called_len = len([called for called in nocall_list if called < 1])
    het_len = sum([gts[0] != gts[1] for gts in variant.genotypes])
    return((het_len / called_len) * 100)

@continuous
def DP_missing(variant):
    miss_idx = [gts[0:2].count(-1) == len(gts[0:2]) for gts in variant.genotypes]
    dp_arr = variant.format('DP')[miss_idx].flatten()
    dp_arr = dp_arr[dp_arr >= 0]
    return dp_arr if dp_arr.size else None

@continuous
def GQ(variant):
    gq = variant.format('GQ').flatten()
    return(gq[gq >= 0])
```

**Comment by pwwang** [comment]
Do you also have aggregation macros combined in your formulas?

**Comment by gnxsf** [comment]
No. The list of macros in the previous post are the only ones I'm using.

**Comment by pwwang** [comment]
Then, are any of the built-in ones, such as SUM and MEAN, used in your FORMULA?

**Comment by gnxsf** [comment]
Good to know. My chromosomes are sorted, so they should already be optimized in that way. For SUM and MEAN, I can understand why the entries need to be stored in memory, but for COUNT, couldn't the program just increment a counter variable instead of storing all the entries?

**Comment by pwwang** [comment]
You will get some sense if you see the source code of `COUNT`. We don't know if we will be counting until you are counting the entries. That's because we don't know the right-hand side of the formula yet. And it is easier to make it general for all aggregations while coding.

I am planning to add a `sorted` under `instance` to indicate that the entries are sorted by groups (the right-hand side of the formula) so that we can do an eager aggregation (run the aggregation once all entries in one group are loaded), instead of waiting to load entries of all groups. It will definitely save the memory use for us.

**Comment by gnxsf** [comment]
Thanks for helping me pinpoint this issue.
