### ISSUE TITLE
Passing VCF context to macros

### ISSUE THREAD

**Issue by kdm9** [pwwang/vcfstats#45]
Hello,

I'm trying to make a `GLOBAL_POS` macro, which calculates `sum(all_previous_chrom_lengths) + variant.POS`. However, getting `all_previous_chrom_lengths` requires reading the `##contig` entries from the VCF header (with `cyvcf2.VCF.seqlens` and `cyvcf2.VCF.seqnames`). As far as I can tell, there is no way to access the `VCF` object in the context of a macro, is this correct? If not, could I please request that some mechanism to achieve the above be added? Perhaps supporting `mymacro(variant, vcf): ...` as an optional arg passed to macro functions that support it? (similar to how input functions in snakemake can use additional arguments beyond just "wildcards", so long as they are given in a specific order or with specific names)

Best,
K

**Comment by pwwang** [comment]
How about:

```python
from vcfstats.macros import continuous

# Say hg19
chrom_lens = [249_250_621, 243_199_373, 198_022_430, 191_154_276, 180_915_260, ...]

def _chrom_to_index(chrom):
  chrom = chrom.replace("chr", "")
  if chrom == "X":
    return 23
  if chrom == "Y":
    return 24
  return int(chrom)

@continuous
def global_pos(variant):
  chr_idx = _chrom_to_index(variant.CHROM)
  prev_chrom_lens = sum(chrom_lens[:chr_idx])
  return prev_chrom_lens + variant.POS
```

**Comment by kdm9** [comment]
Yes, I was  trying to avoid that because we have quite a number of different references we use, and I'd much prefer not to hard code things into the file.

How about injecting a `.vcf` member into the variant object before passing it? e.g. with `setattr(variant, "vcfobj", vcf)` or similar? That shouldn't break any existing code.

Or even

```python

class AugmentedVariant(object):
      def __init__(self, variant, vcf):
            self._variant = variant
            self._vcf = vcf
      def __getattr__(self, attr):
            if attr == "VCF":
                  return self._vcf
            else:
                  return getattr(self._variant, attr)
```

**Comment by pwwang** [comment]
See: https://github.com/pwwang/vcfstats/releases/tag/0.6.0

**Comment by kdm9** [comment]
Brilliant, many thanks! :)
