### ISSUE TITLE
vcfstats error 

### ISSUE THREAD

**Issue by ketkijoshi278** [pwwang/vcfstats#6]
Hello,
I am trying to run vcfstats.
the command:
 vcfstats --vcf GEUVADIS.chr*.vcf.gz --outdir new --formula 'COUNT(1) ~ CONTIG' --title 'Number of variants on each chromosome (modified)' --config config.toml --ggs 'scale_x_discrete(name ="Chromosome", \
limits=c("1","2","3","4","5","6","7","8","9","10","X")) + \
ylab("# Variants")'
the error:
[2021-08-04 09:50:34,888  INFO] 1881217 variants read.
[2021-08-04 09:50:34,889  INFO] [T] Summarizing aggregations ...
[2021-08-04 09:50:34,929  INFO] [T] Composing R code ...
[2021-08-04 09:50:34,934  INFO] [T] Running R code to plot ...
[2021-08-04 09:50:34,934  INFO] [T] Data will be saved to: new/T.txt
[2021-08-04 09:50:34,934  INFO] [T] Plot will be saved to: new/T.col.png
[2021-08-04 09:50:35,631 ERROR] [T] Loading required package: ggplot2
[2021-08-04 09:50:35,632 ERROR] [T] Registered S3 methods overwritten by 'ggplot2':
[2021-08-04 09:50:35,632 ERROR] [T]   method         from
[2021-08-04 09:50:35,632 ERROR] [T]   [.quosures     rlang
[2021-08-04 09:50:35,632 ERROR] [T]   c.quosures     rlang
[2021-08-04 09:50:35,632 ERROR] [T]   print.quosures rlang
[2021-08-04 09:50:35,632 ERROR] [T] Warning messages:
[2021-08-04 09:50:35,633 ERROR] [T] 1: In png(paste0("new/T", ".", figtype, ".png"), height = 2000, width = 2000,  :
[2021-08-04 09:50:35,633 ERROR] [T]   unable to load shared object '/home/kxj190026/anaconda3/envs/chip-seq/lib/R/library/grDevices/libs//cairo.so':
[2021-08-04 09:50:35,633 ERROR] [T]   /home/kxj190026/anaconda3/envs/chip-seq/lib/R/library/grDevices/libs//../../../.././libharfbuzz.so.0: undefined symbol: FT_Done_MM_Var
[2021-08-04 09:50:35,633 ERROR] [T] 2: In png(paste0("new/T", ".", figtype, ".png"), height = 2000, width = 2000,  :
[2021-08-04 09:50:35,633 ERROR] [T]   failed to load cairo DLL
[2021-08-04 09:50:35,633 ERROR] [T] Error: unexpected input in "            p = p + scale_x_discrete(name ="Chromosome", \"
[2021-08-04 09:50:35,633 ERROR] [T] Execution halted

Can you please help me out with this.

**Comment by pwwang** [comment]
It looks like there is a problem with your R. Can you plot something to png in your R console?

**Comment by ketkijoshi278** [comment]
I did capabilities and its showing png as TRUE.
Now when I am trying to write the command its showing me error:
 vcfstats --vcf chr1.vcf.gz --outdir new --formula 'COUNT(1) ~ CONTIG' --title 'Number of variants on each chromosome' --config config.toml
the error:
vcfstats: unrecognized option '--vcf'
Aborted (core dumped)

**Comment by pwwang** [comment]
Could you elaborate what you meant by this?

> I did capabilities and its showing png as TRUE.

**Comment by ketkijoshi278** [comment]
I think the R plot was being made earlier but since I am using linux it was getting generated in Rplot.pdf file. I didn't notice this earlier. When you told me to check whether I am able to create plot. I did that by making basic scatter plot and the plot got generated and store in file Rplot.pdf.
Now when I am again trying to run the command line for vcfstats I am getting error:
like unrecognised option --vcf

**Comment by pwwang** [comment]
You probably have something wrong with the "cairo" lib. Can you try to plot to png file?

**Comment by ketkijoshi278** [comment]
Yes, I am able to do so.[](url)

**Comment by pwwang** [comment]
Could you attach a screenshot running the command with the error?

**Comment by pwwang** [comment]
Are you able to run `vcfstats -l`?

**Comment by ketkijoshi278** [comment]
yes, I am able to run that.
 vcfstats -l
VARTYPE    | categorical     | Variant type, one of deletion, indel, snp or sv
TITV       | categorical     | Tell if a variant is a transition or transversion.
    The variant has to be an snp first.
CONTIG     | categorical     | Get the config/chromosome of a variant. Alias: CHROM
CHROM      | categorical     | Get the config/chromosome of a variant. Alias: CHROM
GTTYPEs    | categorical     | Get the genotypes(HOM_REF,HET,HOM_ALT,UNKNOWN)
    of a variant for each sample
GT_TYPEs   | categorical     | Get the genotypes(HOM_REF,HET,HOM_ALT,UNKNOWN)
    of a variant for each sample
FILTER     | categorical     | Get the FILTER of a variant.
SUBST      | categorical     | Substitution of the variant, including all types of varinat
NALT       | continuous      | Number of alternative alleles
GQs        | continuous      | get the GQ for each sample as a numpy array.
QUAL       | continuous      | Variant quality from QUAL field.
DEPTHs     | continuous      | Get the read-depth for each sample as a numpy array.
DPs        | continuous      | Get the read-depth for each sample as a numpy array.
AAF        | continuous      | Alternate allele frequency across samples in this VCF.
AFs        | continuous      | get the freq of alternate reads as a numpy array.
_ONE       | continuous      | Return 1 for a variant, usually used in aggregation,
    or indication of a distribution plot
COUNT      |                 | Count the variants in groups
SUM        |                 | Sum up the values in groups
MEAN       |                 | Get the mean of the values
AVG        |                 | Get the mean of the values

**Comment by pwwang** [comment]
What are the versions of the dependencies?

```python
import sys, cyvcf2, toml, pyparam, cmdy

print(sys.version)
print(cyvcf2.__version__)
print(toml.__version__)
print(pyparam.__version__)
print(cmdy.__version__)
```

**Comment by ketkijoshi278** [comment]
I reinstalled the software.
and now I am getting this error:
Traceback (most recent call last):
  File "/home1/08259/kjoshi/miniconda3/bin/vcfstats", line 8, in <module>
    sys.exit(main())
  File "/home1/08259/kjosi/miniconda3/lib/python3.8/site-packages/vcfstats/__init__.py", line 172, in main
    ones = get_ones(opts, samples)
  File "/home1/08259/kjoshi/miniconda3/lib/python3.8/site-packages/vcfstats/__init__.py", line 93, in get_ones
    One(formula, opts['title'][i], ggs, devpars[i], opts['outdir'],
  File "/home1/08259/kjoshi/miniconda3/lib/python3.8/site-packages/vcfstats/one.py", line 84, in __init__
    self.datafile = open(self.outprefix + '.txt', 'w')
FileNotFoundError: [Errno 2] No such file or directory: 'new/T.txt'

**Comment by pwwang** [comment]
Create the `new` directory before run the command

**Comment by ketkijoshi278** [comment]
I am able to do it. I reinstalled the software.
Also the R module in my server didn't have png and was showing error in ggplot2.
So i shifted to different version of R.

**Comment by pwwang** [comment]
Great to hear it works for you. 

Feel free to reopen this issue or submit new issues if you have other questions.

**Comment by ketkijoshi278** [comment]
Hey,
I have one more question.
I have 22 vcf files. I want to generate the graph for these files.
I am writing this command:
 vcfstats --vcf  chr*.vcf.gz --outdir new --formula 'COUNT(1) ~ CONTIG' --title 'Number of variants on each chromosome (modified)' --config config.toml --ggs 'scale_x_discrete(name ="Chromosome", \
limits=c("1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22")) + \
ylab("# Variants")'

I wanted to ask whether this is right or wrong? Like will it consider all the 22 vcf files or should I compress them in one file and give that as input?

**Comment by pwwang** [comment]
Do you want a single plot or plots for each chromosome individually?

**Comment by ketkijoshi278** [comment]
I want a single plot but in x axis it should be all chr and on y axis count of variant

**Comment by pwwang** [comment]
Then you should merge them into one vcf file.

**Comment by pwwang** [comment]
Depends on the macro you used. In your case it includes all variants:

See:

https://github.com/pwwang/vcfstats/blob/9b3c9f4773a07713b11ed6cecfb8247d9b6ecdc7/vcfstats/macros.py#L149-L152

**Comment by ketkijoshi278** [comment]
Hey,
I have one more question.
In one of your code you have mentioned Only with SNPs PASS all filters. Can you please let me know what are the filters being appiled?
Also in your  code you are finding alternate allele frequency. Will it be possible to find allele frequency only and plot the graph?

**Comment by pwwang** [comment]
> In one of your code you have mentioned Only with SNPs PASS all filters. Can you please let me know what are the filters being applied?

Any filters listed in the vcf file.

> Also in your code you are finding alternate allele frequency. Will it be possible to find allele frequency only and plot the graph?

What do you mean by "Will it be possible to find allele frequency only and plot the graph?" What else do you want to find and plot?

**Comment by ketkijoshi278** [comment]
Like you have plotted a graph of contig ~AAF. 
I want to make a similar plot or a graph to show distribution of allele frequency in all the chromosomes files.

**Comment by pwwang** [comment]
Is this what you wanted?

https://github.com/pwwang/vcfstats#overall-distribution-of-allele-frequency

It doesn't distinguish chromosomes.

**Comment by ketkijoshi278** [comment]
But this also plots a graph between AAF and contigs.

**Comment by pwwang** [comment]
No, this is no contigs in this plot

![image](https://user-images.githubusercontent.com/1188067/128436324-113e1aec-9769-4b94-9829-6e322eaeaffe.png)

**Comment by ketkijoshi278** [comment]
Can I do this plot but instead of writing AAF i can mention AF? Will this work?

**Comment by pwwang** [comment]
`--ggs 'xlab("AF")'`

**Comment by ketkijoshi278** [comment]
I want to ask one more question is AF same as AAF? I searched in google and it says AF—Allele Frequency for each ALT allele.
Sorry for asking such basic questions. I have never handle a vcf file before.

**Comment by pwwang** [comment]
People use both. But just in case some people get confused with AF being short for allele frequency, AAF is more specific. Allele frequency may not be specific for alternate alleles.

**Comment by ketkijoshi278** [comment]
Ohh okay.
Thank you so much.

**Comment by ketkijoshi278** [comment]
I have one more question. What exactly is config file.In my case the content of my config file is: 

# This is a TOML document.

title = "TOML Example"

[owner]
name = "Tom Preston-Werner"
dob = 1979-05-27T07:32:00-08:00 # First class dates

[database]
server = "192.168.1.1"
ports = [ 8000, 8001, 8002 ]
connection_max = 5000
enabled = true

[servers]

  # Indentation (tabs and/or spaces) is allowed but not required
  [servers.alpha]
  ip = "10.0.0.1"
  dc = "eqdc10"

  [servers.beta]
  ip = "10.0.0.2"
  dc = "eqdc10"

[clients]
data = [ ["gamma", "delta"], [1, 2] ]

# Line breaks are OK when inside arrays
hosts = [
  "alpha",
  "omega"
]


Is this right?

**Comment by pwwang** [comment]
Will this help you understand it?

https://en.m.wikipedia.org/wiki/Configuration_file

**Comment by ketkijoshi278** [comment]
Oh okay. I will go through the above link.
Do i need to specify some ggplot parameters in config file?

**Comment by ketkijoshi278** [comment]
Also I am trying to generate output using this command but I am getting error as segmentation fault.
The command: 
vcfstats --vcf allfiles1.vcf.gz --outdir new --formula 'COUNT(1, VARTYPE[snp]) ~ SUBST[A>T,A>G,A>C,T>A,T>G,T>C,G>A,G>T,G>C,C>A,C>T,C>G]' --title 'Number of substitutions of SNPs' --config config.toml

**Comment by pwwang** [comment]
what's in your config file?

**Comment by ketkijoshi278** [comment]
This is the content of my config file:
# This is a TOML document.

title = "TOML Example"

[owner]
name = "Tom Preston-Werner"
dob = 1979-05-27T07:32:00-08:00 # First class dates

[database]
server = "192.168.1.1"
ports = [ 8000, 8001, 8002 ]
connection_max = 5000
enabled = true

[servers]

  # Indentation (tabs and/or spaces) is allowed but not required
  [servers.alpha]
  ip = "10.0.0.1"
  dc = "eqdc10"

  [servers.beta]
  ip = "10.0.0.2"
  dc = "eqdc10"

[clients]
data = [ ["gamma", "delta"], [1, 2] ]

# Line breaks are OK when inside arrays
hosts = [
  "alpha",
  "omega"
]

I know I should add some parameters related to ggplot. But I am not able to understand how to do it.

**Comment by pwwang** [comment]
It is completely unrelated. Here is an example:

https://github.com/pwwang/vcfstats/blob/master/examples/config.toml

**Comment by ketkijoshi278** [comment]
Hey, I am getting this error:
Traceback (most recent call last):
  File "/home1/08259/kjoshi/miniconda3/bin/vcfstats", line 8, in <module>
    sys.exit(main())
  File "/home1/08259/kjoshi/miniconda3/lib/python3.8/site-packages/vcfstats/__init__.py", line 167, in main
    load_config(opts['config'], opts)
  File "/home1/08259/kjoshi/miniconda3/lib/python3.8/site-packages/vcfstats/__init__.py", line 146, in load_config
    opts['title'].append(one['title'])
AttributeError: 'str' object has no attribute 'append'

**Comment by pwwang** [comment]
Could you provide full information, including the command you run and the config file?

**Comment by ketkijoshi278** [comment]
Sure this is the command I ran:
 vcfstats --vcf allfiles.vcf.gz --outdir new --formula 'COUNT(1, VARTYPE[snp]) ~ SUBST[A>T,A>G,A>C,T>A,T>G,T>C,G>A,G>T,G>C,C>A,C>T,C>G]' --title 'Number of substitutions of SNPs' --config config.toml

The config file:

title = "TOML Example"

[owner]
name = "Tom Preston-Werner"
dob = 1979-05-27T07:32:00-08:00 # First class dates

[database]
server = "192.168.1.1"
ports = [ 8000, 8001, 8002 ]
connection_max = 5000
enabled = true

[servers]

  # Indentation (tabs and/or spaces) is allowed but not required
  [servers.alpha]
  ip = "10.0.0.1"
  dc = "eqdc10"

  [servers.beta]
  ip = "10.0.0.2"
  dc = "eqdc10"

[clients]
data = [ ["gamma", "delta"], [1, 2] ]

[[one]]
formula = 'DEPTHs{0} ~ CHROM'
title = 'Depth distribution on each chromosome'
ggs = 'theme_minimal()'
devpars = {width = 1000, height = 1000, res = 100}

[[one]]
formula = 'AAF ~ CHROM'
title = 'Allele frequency distribution on each chromosome'
ggs = 'theme_bw()'
devpars = {width = 2000, height = 2000, res = 300}

[[one]]
formula = 'COUNT(1, VARTYPE[snp]) ~ SUBST[A>T,A>G,A>C,T>A,T>G,T>C,G>A,G>T,G>C,C>A,C>T,C>G]'
title = 'Number of substitutions of SNPs'
ggs = 'theme_bw()'
devpars = {width = 2000, height = 2000, res = 300}

**Comment by pwwang** [comment]
Your `title` in config file overrides the one from command line.

**Comment by ketkijoshi278** [comment]
so should the title file just consist of this:
passed = true

[[one]]
formula = 'COUNT(1, group=VARTYPE) ~ CHROM'
ggs = 'theme_minimal()'
devpars = {width = 1000, height = 1000, res = 100}

**Comment by pwwang** [comment]
That should be legal.

**Comment by ketkijoshi278** [comment]
I did that. Now I am running this command.
vcfstats --vcf allfiles.vcf.gz --outdir new --formula 'COUNT(1, group=VARTYPE) ~ CHROM' --title 'Types of variants on each chromosome' --config config.toml

But still getting error:
The error:
Traceback (most recent call last):
  File "/home1/08259/kjoshi/miniconda3/bin/vcfstats", line 8, in <module>
    sys.exit(main())
  File "/home1/08259/kjoshi/miniconda3/lib/python3.8/site-packages/vcfstats/__init__.py", line 167, in main
    load_config(opts['config'], opts)
  File "/home1/08259/kjoshi/miniconda3/lib/python3.8/site-packages/vcfstats/__init__.py", line 144, in load_config
    raise ValueError("Title not found in instance: {}".format(one))
ValueError: Title not found in instance: {'formula': 'COUNT(1, group=VARTYPE) ~ CHROM', 'ggs': 'theme_minimal()', 'devpars': {'width': 1000, 'height': 1000, 'res': 100}}

**Comment by pwwang** [comment]
Try adding a title in your config file:

```toml
passed = true

[[one]]
title = 'Number of variants'
formula = 'COUNT(1, group=VARTYPE) ~ CHROM'
ggs = 'theme_minimal()'
devpars = {width = 1000, height = 1000, res = 100}
```

**Comment by ketkijoshi278** [comment]
I did this. I edited the config file according to above comment. But I am getting error.
the commands:
 vcfstats --vcf allfiles.vcf.gz --outdir new --formula 'COUNT(1, group=VARTYPE) ~ CHROM' --title 'Types of variants on each chromosome' --config config.toml

the error:
[2021-08-06 13:49:56,574 DEBUG] - Parsing item 'config.toml'
[2021-08-06 13:49:56,574 DEBUG]   Previous: <ParamAuto(-c, --config :: auto) @ 47461151266464>
[2021-08-06 13:49:56,574 DEBUG]   Matched: None, name=None, type=None, value='config.toml'
[2021-08-06 13:49:56,574 DEBUG]   Param '-c, --config' consumes 'config.toml'
[2021-08-06 13:49:56,574 DEBUG]   Closing final argument: '-c, --config'
Traceback (most recent call last):
  File "/home1/08259/kjoshi/miniconda3/bin/vcfstats", line 8, in <module>
    sys.exit(main())
  File "/home1/08259/kjoshi/miniconda3/lib/python3.8/site-packages/vcfstats/__init__.py", line 167, in main
    load_config(opts['config'], opts)
  File "/home1/08259/kjoshi/miniconda3/lib/python3.8/site-packages/vcfstats/__init__.py", line 149, in load_config
    def_devpars = default_devpars.copy()
AttributeError: 'Namespace' object has no attribute 'copy'

**Comment by pwwang** [comment]
What's the version of your `vcfstats`?

**Comment by ketkijoshi278** [comment]
vcfstats v0.0.6: Powerful VCF statistics.

**Comment by pwwang** [comment]
Could you try v0.1.0?

```
pip install -U vcfstats
```

**Comment by ketkijoshi278** [comment]
I update the software but its shows me error.
the command:
vcfstats --vcf allfiles.vcf.gz --outdir new --formula 'COUNT(1, group=VARTYPE)~CHROM' --title 'Types of variants on each chromosome' --config config.toml
the error:
Traceback (most recent call last):
  File "/home1/08259/kjoshi/miniconda3/bin/vcfstats", line 8, in <module>
    sys.exit(main())
  File "/home1/08259/kjoshi/miniconda3/lib/python3.8/site-packages/vcfstats/cli.py", line 156, in main
    load_config(opts['config'], opts)
  File "/home1/08259/kjoshi/miniconda3/lib/python3.8/site-packages/vcfstats/cli.py", line 138, in load_config
    def_devpars = default_devpars.copy()
AttributeError: 'Namespace' object has no attribute 'copy'passed = true

the config file:
[[one]]
title = 'Types of variants on each chromosome'
formula = 'COUNT(1, group=VARTYPE) ~ CHROM'
ggs = 'theme_minimal()'
devpars = {width = 1000, height = 1000, res = 100}

**Comment by pwwang** [comment]
Looks like the dependencies haven't been updated.

What's the versions of `pyparam`?
```
python -c 'import pyparam; print(pyparam.__version__)'
```

**Comment by ketkijoshi278** [comment]
this is the version of pyparam.
0.4.8

**Comment by ketkijoshi278** [comment]
I updated it 
the command use for that:
 pip install -U pyparam
output of that:
Attempting uninstall: rich
    Found existing installation: rich 6.2.0
    Uninstalling rich-6.2.0:
      Successfully uninstalled rich-6.2.0
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

vcfstats 0.1.0 requires rich<7.0.0,>=6.0.0, but you'll have rich 9.13.0 which is incompatible.
Successfully installed rich-9.13.0

**Comment by pwwang** [comment]
And version of `simpleconf`?

```
python -c 'import simpleconf; print(simpleconf.__version__)'
```

**Comment by ketkijoshi278** [comment]
simpleconf version is
0.4.0

**Comment by pwwang** [comment]
Can you add this to your config file:

```toml
devpars = { width = 600, height = 600, res = 100}
```

before `[[one]]`

**Comment by ketkijoshi278** [comment]
Yes, I did that. But now I am getting Segmentation fault error

**Comment by pwwang** [comment]
Segmentation fault error is very likely due to `cyvcf2` parsing the vcf file. It's c-backended. You might have something wrong with your vcf file. Can you run the command with the example vcf file that `vcfstats` provided?

**Comment by ketkijoshi278** [comment]
Yes, I am able to run it using sample.vcf provided by you.
I actually was able to run one of the vcfstats command (first command which plot no. of variants for each chromosome) on my vcf file and I got output. 
I am not able to understand why its showing segmentation fault now.

**Comment by ketkijoshi278** [comment]
Is there any way I could correct my vcf files? Any software which could format the vcf files?

**Comment by pwwang** [comment]
What about this one?

https://vcftools.github.io/perl_module.html#vcf-validator

I myself haven't used any this kind of tools.

**Comment by ketkijoshi278** [comment]
Hey,
I am able to do so. the error was related to merging of all the vcf files. I correct that with using bcftools merge option.

**Comment by ketkijoshi278** [comment]
vcfstats --vcf examples/sample.vcf \
	--outdir examples/ \
	--formula 'AAF ~ CONTIG[1,2]' \
	--title 'Allele frequency on chromosome 1,2' \
	--config examples/config.toml \
	--figtype density
In this code I have one question.
Suppose I want to show AF density distribution for chr 22,21,20 and 19
should I use CONTIG[22,21,20,19]?

**Comment by pwwang** [comment]
Yes

**Comment by ketkijoshi278** [comment]
vcfstats --vcf Merged1.vcf.gz --outdir new/ --formula 'COUNT(1, group=GTTYPEs[HET,HOM]{0}) ~ CHROM' --title 'Mutant genotypes on each chromosome' --config config.toml
While running this command i am getting error
the error:
Traceback (most recent call last):
  File "/home1/08259/kjoshi/miniconda3/bin/vcfstats", line 8, in <module>
    sys.exit(main())
  File "/home1/08259/kjoshi/miniconda3/lib/python3.8/site-packages/vcfstats/cli.py", line 166, in main
    one.iterate(variant)
  File "/home1/08259/kjoshi/miniconda3/lib/python3.8/site-packages/vcfstats/one.py", line 108, in iterate
    self.formula.run(variant, self.datafile)
  File "/home1/08259/kjoshi/miniconda3/lib/python3.8/site-packages/vcfstats/formula.py", line 288, in run
    self.Y.run(variant, self.passed)
  File "/home1/08259/kjoshi/miniconda3/lib/python3.8/site-packages/vcfstats/formula.py", line 194, in run
    group = self.group.run(variant, passed)
  File "/home1/08259/kjoshi/miniconda3/lib/python3.8/site-packages/vcfstats/formula.py", line 126, in run
    value = [value[sidx] for sidx in self.samples]
  File "/home1/08259/kjoshi/miniconda3/lib/python3.8/site-packages/vcfstats/formula.py", line 126, in <listcomp>
    value = [value[sidx] for sidx in self.samples]
TypeError: list indices must be integers or slices, not Token

**Comment by pwwang** [comment]
Your formula is incorrect.

Could you read through the doc?

https://vcfstats.readthedocs.io/en/latest/formulas/

**Comment by pwwang** [comment]
Your formula is incorrect. Try:

```
vcfstats --vcf Merged1.vcf.gz --outdir new/ --formula 'COUNT(1, group=GTTYPEs) ~ CHROM' --title 'Mutant genotypes on each chromosome' --config config.toml
```

**Comment by ketkijoshi278** [comment]
I followed your commmand but it still showing error;
vcfstats --vcf Merged1.vcf.gz --outdir new/ --formula 'COUNT(1, group=GTTYPEs) ~ CHROM' --title 'Mutant genotypes on each chromosome' --config config.toml
[08/10/21 17:07:04] INFO     Combining regions, remind that regions should not be overlapping ...                                                                                                                                            
                    INFO     Getting vcf handler by given regions ...                                                                                                                                                                        
[W::bcf_hdr_check_sanity] GL should be declared as Number=G
                    INFO     Getting instances ...                                                                                                                                                                                            
                    INFO     INSTANCE: 'Mutant genotypes on each chromosome'                                                                                                                                                                  
                    INFO     [Mutant genotypes on each chromosome] Parsing formulas ...                                                                                                                                                      
                    INFO     [Mutant genotypes on each chromosome] plot type: col                                                                                                                                                            
                    INFO     INSTANCE: 'Types of variants on each chromosome'                                                                                                                                                                
                    INFO     [Types of variants on each chromosome] Parsing formulas ...                                                                                                                                                      
                    INFO     [Types of variants on each chromosome] plot type: col                                                                                                                                                            
                    INFO     Start reading variants ...                                                                                                                                                                                      
Traceback (most recent call last):
  File "/home1/08259/kjoshi/miniconda3/bin/vcfstats", line 8, in <module>
    sys.exit(main())
  File "/home1/08259/kjoshi/miniconda3/lib/python3.8/site-packages/vcfstats/cli.py", line 166, in main
    one.iterate(variant)
  File "/home1/08259/kjoshi/miniconda3/lib/python3.8/site-packages/vcfstats/one.py", line 108, in iterate
    self.formula.run(variant, self.datafile)
  File "/home1/08259/kjoshi/miniconda3/lib/python3.8/site-packages/vcfstats/formula.py", line 288, in run
    self.Y.run(variant, self.passed)
  File "/home1/08259/kjoshi/miniconda3/lib/python3.8/site-packages/vcfstats/formula.py", line 198, in run
    raise ValueError("Cannot aggregate on more than one group, " + \
ValueError: Cannot aggregate on more than one group, make sure you specified sample for sample data.

**Comment by pwwang** [comment]
Let's move the conversations here:

https://gitter.im/vcfstats/questions
