### ISSUE TITLE
SVG format

### ISSUE THREAD

**Issue by Talo07** [pwwang/vcfstats#8]
Dear colleagues, is it possible to get a figure in SVG format directly after excusing vcfstats instead of PNG format?

Thanks in advance

**Comment by pwwang** [comment]
It's not supported yet. 

Current workaround:

After run the command, find the `xxx.plot.R` file in the output directory, change `png("xxx.png")` to `svg("xxx.svg")` and run it with `Rscript xxx.plot.R`

**Comment by pwwang** [comment]
A `figfmt` option is added in #12 (0.2.0). You can pass `--figfmt svg` to generate svg format figures or use a configuration file:

```toml
figfmt = "svg"
```
